FROM node:20-slim

ENV HOME=/app \
    XDG_CACHE_HOME=/app/.cache

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --no-frozen-lockfile \
 && pnpm next telemetry disable || true

# Do NOT copy the entire source code here — it's mounted in docker-compose

EXPOSE 3000

CMD ["pnpm", "dev", "--port", "3000", "--hostname", "0.0.0.0"]
