export const DEVICE_PROFILES = {
  Placeholder: "Please Select your E-Reader",
  K1: "Kindle 1",
  K2: "Kindle 2",
  K3: "Kindle 3",
  K34: "Kindle Keyboard/Touch",
  K57: "Kindle 5/7",
  KPW: "Kindle Paperwhite 1/2",
  KV: "Kindle Voyage",
  KPW34: "Kindle Paperwhite 3/4/Oasis",
  K810: "Kindle 8/10",
  KO: "Kindle Oasis 2/3/Paperwhite 12",
  K11: "Kindle 11",
  KPW5: "Kindle Paperwhite 5/Signature Edition",
  KS1860: "Kindle Scribe 1860",
  KS1920: "Kindle Scribe 1920",
  KoMT: "Kobo Mini/Touch",
  KoG: "Kobo Glo",
  KoGHD: "Kobo Glo HD",
  KoA: "Kobo Aura",
  KoAHD: "Kobo Aura HD",
  KoAH2O: "Kobo Aura H2O",
  KoAO: "Kobo Aura ONE",
  KoN: "Kobo Nia",
  KoC: "Kobo Clara HD/Kobo Clara 2E",
  KoCC: "Kobo Clara Colour",
  KoL: "Kobo Libra H2O/Kobo Libra 2",
  KoLC: "Kobo Libra Colour",
  KoF: "Kobo Forma",
  KoS: "Kobo Sage",
  KoE: "Kobo Elipsa",
  KCS: "Kindle Colorsoft",
  Rmk1: "reMarkable 1",
  Rmk2: "reMarkable 2",
  RmkP: "reMarkable Paper Pro",
  Other: "Other",
}
