export enum JobStatus {
  UPLOADING = 'UPLOADING',
  QUEUED = 'QUEUED',
  PROCESSING = 'PROCESSING',
  COMPLETE = 'COMPLETE',
  DOWNLOADED = 'DOWNLOADED',
  ERRORED = 'ERRORED',
  CANCELLED = 'CANCELLED',
  ABANDONED = 'ABANDONED',
}
