name: Conversion Issue
description: Report a problem with manga/comic conversion
title: "[Conversion]: "
labels: ["conversion", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Report issues related to converting manga/comics (CBZ, CBR, PDF, etc.) to other formats.

  - type: dropdown
    id: input-format
    attributes:
      label: Input Format
      description: What format is your source file?
      options:
        - CBZ (Comic Book Zip)
        - CBR (Comic Book RAR)
        - PDF
        - CB7 (Comic Book 7z)
        - Directory of images
        - Other
    validations:
      required: true

  - type: dropdown
    id: output-format
    attributes:
      label: Desired Output Format
      description: What format are you trying to convert to?
      options:
        - EPUB
        - MOBI
        - KFX
        - CBZ
        - PDF
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Conversion Issue
      description: What went wrong with the conversion?
      placeholder: |
        Describe the problem:
        - Conversion failed completely
        - Output quality issues (images blurry, cropped, etc.)
        - Missing pages
        - File size issues
        - Metadata problems
    validations:
      required: true

  - type: input
    id: file-size
    attributes:
      label: Input File Size
      description: Approximate size of the input file
      placeholder: "e.g., 150MB"
    validations:
      required: false

  - type: input
    id: page-count
    attributes:
      label: Number of Pages/Images
      description: Approximate number of pages or images in the source
      placeholder: "e.g., 200 pages"
    validations:
      required: false

  - type: textarea
    id: conversion-settings
    attributes:
      label: Conversion Settings
      description: What settings did you use? (if any custom settings were applied)
      placeholder: |
        - Format: EPUB
        - Quality: High
        - Resize: Enabled
        - etc.
    validations:
      required: false

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: Full error message from the application or logs
      placeholder: Paste the error message here...
      render: shell
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: How are you running the application?
      options:
        - Docker (production single-container)
        - Docker (development multi-container)
        - Local development
        - Other
    validations:
      required: true

  - type: textarea
    id: worker-logs
    attributes:
      label: Celery Worker Logs
      description: Logs from the Celery worker (if available)
      placeholder: |
        docker logs mangaconverter-foss-prod
        or
        docker-compose logs celery-worker
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: sample-file
    attributes:
      label: Sample File
      description: Can you provide a sample file that reproduces the issue?
      options:
        - label: I can provide a sample file (attach or link below)
          required: false
        - label: This issue occurs with publicly available files (provide link/source below)
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (file source, specific manga title if publicly available, screenshots, etc.)
      placeholder: Any other details...
    validations:
      required: false
